name: CI Workflows

on:
  workflow_call:
    inputs:
      app_name: 
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout repo"
      uses: actions/checkout@v2
    
    - name: "Setup node"
      uses: actions/setup-node@v2
      with: 
        node-version: 16
    
    - name: "Install dependencies"
      run: npm install
  
  test:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: "Setup node"
        uses: actions/setup-node@v2
        with: 
          node-version: 16

      - name: Start job
        run: echo "Starting to build ${{ inputs.app_name }}"
      
      - name: "Test dependencies"
        run: |
          npm install \
          npm test
        
      - name: "Clarification"
        run: echo "Test complete from RW GHA"

  scan:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - name: Start job
        run: echo "Starting to test ${{ inputs.app_name }}"
      - name: "setup node"
        uses: actions/setup-node@v2
        with: 
          node-version: 16
      
      - name: "Security scan"
        run: |
          npm i --package-lock-only
          npm audit --audit-level=high